### ISSUE TITLE
run quokka: start on current page, just got Unexpected character '@'

### ISSUE THREAD

**Issue by azl397985856** [wallabyjs/quokka-react-sample#1]
here is the error message:
​​​​
Quokka #1 (node: v6.11.1)​​​​
​​Failed to parse src/modules/welcome/quokka.js, SyntaxError: Unexpected character '@' (38:0)​​
​​    at _combinedTickCallback (internal/process/next_tick.js:73:7)​​
​​    at process._tickCallback (internal/process/next_tick.js:104:9)​​
​​    at _combinedTickCallback (internal/process/next_tick.js:73:7)​​
​​    at process._tickCallback (internal/process/next_tick.js:104:9)​​

AND  .babelrc
{
    "presets": [
        "es2015",
        "stage-0",
        "stage-1",
        "react"
    ],
    "plugins": ["babel-plugin-transform-decorators-legacy"]
}

AND the jsx:
({
  babel: true,
  plugins: ["babel-plugin-transform-decorators-legacy"]
});
...
@connect(mapStateToProps, mapDispatchToProps)
export default class Welcome extends Component {
  render() {}
}

**Comment by ArtemGovorov** [comment]
Just tried your sample in the repo and (after installing missing babel plugins) everything is working for me:

![screen shot 2017-08-02 at 8 17 45 pm](https://user-images.githubusercontent.com/979966/28869328-b169b58c-77bf-11e7-81b5-c6bc0705078e.png)

First, you don't need this line:
```diff
({
  babel: true,
- plugins: ["babel-plugin-transform-decorators-legacy"]
});
```
because it is a place for quokka plugins, not babel plugins. [Babel plugins should be listed under the babel property](https://quokkajs.com/docs/configuration.html#overriding-babel-settings):

```
({
  babel: {
    plugins: ["babel-plugin-transform-decorators-legacy"]
  }
});
```

However, you don't need to list your plugins, because you have `.babelrc` that has the plugin configured. So this:

```
({
  babel: true
});
```
should be enough.

Second, according to your Quokka log, babel is not loaded. This means that you probably don't have quokka config: 

```
({
  babel: true
});
```
at the very top of your file. It must be the very first thing in the file (before anything, even imports).

Alternatively, you may configure quokka to use babel [always via global config file, or for this project in the package.json](https://quokkajs.com/docs/configuration.html).

Hope it helps.

**Comment by azl397985856** [comment]
it doesn't not work probably~

![image](https://user-images.githubusercontent.com/12479470/28920105-fb249ed0-7882-11e7-9fe9-1535c542f04a.png)

**Comment by ArtemGovorov** [comment]
It looks better now, as you can see babel is now present in quokka header. However, it now looks like your `.babelrc` is not applied for some reason. Unfortunately, I can't reproduce it on this repo.

I have created this branch with your config files: https://github.com/wallabyjs/quokka-react-sample/tree/issue-1, running Quokka on the https://github.com/wallabyjs/quokka-react-sample/blob/issue-1/src/modules/welcome/test.js file and everything is working. try cloning the repo and running Quokka on the file. If it works, try adding the missing bits from your project to reproduce the issue.

**Comment by azl397985856** [comment]
thank your very much. i will try it
